### ISSUE TITLE
Support environment variables

### ISSUE THREAD

**Issue by rocketraman** [jdiazcano/cfg4k#14]
Support binding environment variables to configuration (12-factor app compatible).

Spring Boot does a particularly good job at this, by mapping properties defined internally to corresponding idiomatic environment variable syntax e.g. `foo.bar.baz` -> `FOO_BAR_BAZ`. They also support some flexibility in the mapping ([relaxed binding](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-relaxed-binding)).

Cfg4j on the other hand does a poor job of this, unless its improved since the last time I looked at cfg4j.

**Comment by jdiazcano** [comment]
@rocketraman I have done this:

1. FOO_BAR_BAZ -> foo.bar.baz
2. FOO-BAR-BAZ -> foo.bar.baz

So now you can have environment variables and use them like that. Any other improvements?

**Comment by rocketraman** [comment]
Awesome. Personally, I could do without the version with "-"; environment variables use `_` pretty idiomatically. I would add a couple more to deal flexibly with camelcase:

```
FOO_BAR_BAZ ->  fooBar.baz
FOOBAR_BAZ ->  fooBar.baz
```

**Comment by jdiazcano** [comment]
Transformations can be applied easily but my question is: How would I detect that FOOBAR are two words?

**Comment by rocketraman** [comment]
> Transformations can be applied easily but my question is: How would I detect that FOOBAR are two words?

Are you not seeing the property names that need to be bound, and then going to look for sources? For example, if I want to bind property `fooBar.baz`, I would see if env variable `FOO_BAR_BAZ` or `FOOBAR_BAZ` exists.

If you are going from sources to property names, then I guess you can't do this easily. But wouldn't this approach result in too many bindings? And how would you look up properties in remote sources that can't provide a list of their contents?

**Comment by jdiazcano** [comment]
It's not a mapping exactly, I just extract the environment variables, transform it and add it to the map properties.

I will give this a second thought then

**Comment by jdiazcano** [comment]
I have been thinking about this:

1. If I can't get a list of properties when initialising the loader then the maker of the Loader/Provider will be the one who will have to cache them or make the call once it's asked. I think that is responsibility for each Loader/Provider.

2. Then I think two kind of Loaders should be done, `CachedEnvironmentConfigLoader` and `EnvironmentConfigLoader`, one will do the transformations and load all of them at load time so no performance hit when getting a setting. And the second one would apply the transformations at runtime and the other way around, from `fooBar.baz` to `FOO_BAR_BAZ` and try to get that Environment variable.

Does it sound better?

**Comment by rocketraman** [comment]
That sounds great. If your Loader interface is able to handle both a "pull" and "push" then it is flexible enough to handle both types of cases embodied by `CachedEnvironmentConfigLoader` and `EnvironmentConfigLoader`.

That being said, I would question the need for `CachedEnvironmentConfigLoader` at all. The JVM loads environment variables into memory at startup already, so I doubt caching them will make any meaningful performance difference.

**Comment by jdiazcano** [comment]
The JVM loads the environment variables into memory but doesn't apply the transformations, and doing the transformations everytime someone ask for a setting I think would be worse that caching them once into "standard" dot notation config

**Comment by rocketraman** [comment]
Also: related to environment variables, java also has "system properties" as you know. Once you have an implementation for env variables, it should be trivial to support system properties too. Spring Boot has a defined precedence i.e. in general properties are obtained in order of:

1. system properties
2. environment variables
3. bundled config file

The actual precedence in Spring Boot is more flexible (and complicated) and IMO not necessary for cfg4k, but for reference it is:

https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

**Comment by jdiazcano** [comment]
Yes! Look at the merge I just did. It is for supporting these, a real simple Loader that relies on the call for System.getProperty()

I think Spring does too much and this library in my opinion should stay easy to use as it is right now.

In order to do that you would:

```kotlin
fun main(args: Array<String>) {
    val provider = OverrideConfigProvider(arrayOf(
            SystemPropertyConfigLoader(),
            EnvironmentConfigLoader(),
            JsonConfigLoader(SystemPropertyConfigLoader::class.java.getResource("settings.json"))
    )
    )
}
```

**Comment by rocketraman** [comment]
> I think Spring does too much and this library in my opinion should stay easy to use as it is right now.

Agreed.

> The JVM loads the environment variables into memory but doesn't apply the transformations, and doing the transformations everytime someone ask for a setting I think would be worse that caching them once into "standard" dot notation config

I'm a bit confused, and perhaps I just don't understand your terminology. Let me try a use case.

My program defines a config property `fooBar.baz` which I want to inject into the constructor of a class. What I want to do as a user (ignoring system props for now) is:

1) See if either `FOOBAR_BAZ` or `FOO_BAR_BAZ` (transformed from `fooBar.baz`) exists in the environment, and if one does, use its value, and stop here.

2) Otherwise, see if `fooBar.baz` exists in the bundled config, and if it does, use its value.

So the "transformation" I'm thinking of is only in step 1 and only applicable to `EnvironmentConfigLoader`, and could be cached there. Where have I gone wrong?

**Comment by jdiazcano** [comment]
I see what you say. I will do it that way, I like it.

**Comment by jdiazcano** [comment]
I have added the environment variable loader. If you could take some minutes to test it would be awesome!

If you ask for fooBar, it will get the FOO_BAR property. Same for foo.bar

I will cache them so the next time you ask for that property it will know where to find it. When reloading it clears the cache and tries again if you ask for it another time.

What I am not sure if different transformations should be applied everytime for your "fooBar.baz" example. I have never had the need to mix notations in these names.

**Comment by rocketraman** [comment]
> What I am not sure if different transformations should be applied everytime for your "fooBar.baz" example. I have never had the need to mix notations in these names.

By `fooBar.baz`, what I really meant was a hierarchical config entry that may be represented in yaml as follows:

```
fooBar:
  baz: whatever
```

Which presumably is equivalent to a properties file like:

```
fooBar.baz = whatever
```

IMO, when mapping hierarchies like that to environment variables, the levels should be separated by `_` (which is what I think you already did), so the end result would be `FOO_BAR_BAZ` or `FOOBAR_BAZ` depending on how the user decides to do the camel case conversion.

Note that I'm getting a test failure on the current master (9d2d3c9):

```
Jan 19, 2017 8:29:14 PM org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry loadTestEngines
INFO: Discovered TestEngines with IDs: [spek]

Failures (1):
  Spek:com.jdiazcano.konfig.ConfigLoaderTest:describe a environment config loader:it a value should be b
    => java.lang.AssertionError:  should be equal bar

Test run finished after 23387 ms
[        33 containers found      ]
[         0 containers skipped    ]
[        33 containers started    ]
[         0 containers aborted    ]
[        33 containers successful ]
[         0 containers failed     ]
[        64 tests found           ]
[         0 tests skipped         ]
[        64 tests started         ]
[         0 tests aborted         ]
[        63 tests successful      ]
[         1 tests failed          ]

:cfg4k-core:junitPlatformTest FAILED
```

**Comment by jdiazcano** [comment]
In the test it says: ConfigLoaderTest:describe a environment config loader

If you go to that test you will see a javadoc comment saying that you have to pass some environment variables for it to pass. Every computer and OS is different so I couldn't define an environment variable that worked with everything. I know it is not ideal for tests but it's the best I could come up with

**Comment by rocketraman** [comment]
> In the test it says: ConfigLoaderTest:describe a environment config loader

Ok cool -- strange that the standard way of specifying gradle environment vars for tests doesn't seem to work. Perhaps it is because of Spek?

I note your test cases don't have a case for camel case conversion. Will camel case e.g. `fooBar` be converted to `FOOBAR` always? I kind of like that actually -- keeps it simple and consistent.

**Comment by jdiazcano** [comment]
It is implemented but I forgot to write a test for it. I can remove it since it is just a transformation (one line).

Anyways, new transformations can be added to the loader (custom ones) like this:

```kotlin
val loader = EnvironmentConfigLoader()
loader.addTransformer {
    it.replace('foo', 'bar')
}
```

What would you do? In my opinion I would do not include it in the default transformers but if you say it is useful then I will leave it

**Comment by rocketraman** [comment]
> In my opinion I would do not include it in the default transformers

Makes sense to me. Keep the default behavior as predictable as possible.

To keep it flexible, it might useful for callers of the library to be able to specify their desired transformers when the loader is constructed, OR add to the existing transformer list after construction. Maybe not in the first version though -- see if its something people ask for.

**Comment by jdiazcano** [comment]
There is no test but it is actually implemented. Then I will close this, I will remove that transformer.
