### ISSUE TITLE
EnvironmentConfigLoader and SystemPropertyConfigLoader returning "" for any key

### ISSUE THREAD

**Issue by sleonidy** [jdiazcano/cfg4k#21]
Hi,
EnvironmentConfigLoader and SystemPropertyConfigLoader  loaders are returning empty string for any key. So they are not usable in case of OverrideConfigProvider, when first provider is one of above.

**Comment by jdiazcano** [comment]
Working on it

**Comment by jdiazcano** [comment]
Fixed and pushed to 0.7.2 is now synchronizing on bintray!
