### ISSUE TITLE
FileChangeReloadStrategy watcher uses incorrect test

### ISSUE THREAD

**Issue by rocketraman** [jdiazcano/cfg4k#40]
The `FileChangeReloadStrategy` watcher uses an incorrect test to check if the event corresponds to the configuration file.

The javadocs for `WatchEvent.context` [state](https://docs.oracle.com/javase/8/docs/api/java/nio/file/WatchEvent.html#context--) that the path returned is relative to the parent on which the watch is registered.

However, the current code just naively does `fileName == file`. The following code seems to be a pretty foolproof way of doing the correct test:

`parent.resolve(fileName).toRealPath() == file.toRealPath()`

**Comment by rocketraman** [comment]
Ah, I see this was fixed in 42983115d877cb3b8533b0273c7dcf4252af516d. Though I think that it will still fail in certain situations with soft links, since `toRealPath` is still not part of the test.

**Comment by jdiazcano** [comment]
I will probably change it to `toRealPath()` but I still need to read more docs about it.

Sorry for the delay!

**Comment by jdiazcano** [comment]
Changed!
