### ISSUE TITLE
Hocon config mapper does not handle nulls

### ISSUE THREAD

**Issue by rocketraman** [jdiazcano/cfg4k#52]
The Hocon config mapper does not handle nulls.

https://github.com/jdiazcano/cfg4k/blob/master/cfg4k-hocon/src/main/kotlin/com/jdiazcano/cfg4k/hocon/HoconConfigMapper.kt#L19

According to the docs, `value.unwrapped()` can return `null` (which it does when the hocon config is something like `value = null`). This should get passed through to support setting `null` when the config interface defines a nullable type.

**Comment by jdiazcano** [comment]
This is fixed in:

* https://github.com/jdiazcano/cfg4k/commit/87821b6b7587c5c865fdd6286bf88fb14735f305
* https://github.com/jdiazcano/cfg4k/commit/9826f44f410681756a2f1c6ae2005e5102edcd14

If you need a release for this ping me in Slack, if not I'll wait for #48 which should be soon done.
