### ISSUE TITLE
[BUG] Unexpected crash in DefaultConfigLoader.get with IllegalArgumentException: Trying to get a key from a primitive

### ISSUE THREAD

**Issue by credmond-git** [jdiazcano/cfg4k#63]
**Describe the bug**
Since upgrading to com.jdiazcano.cfg4k:cfg4k-core:0.9.41 i am getting the following crash

Exception in thread "main" java.lang.IllegalArgumentException: Trying to get a key from a primitive
	at com.jdiazcano.cfg4k.loaders.DefaultConfigLoader.get(DefaultConfigLoader.kt:27)
	at com.jdiazcano.cfg4k.providers.DefaultConfigProvider.get(DefaultConfigProvider.kt:51)
	at com.jdiazcano.cfg4k.providers.CachedConfigProvider.get(CachedConfigProvider.kt:37)
	at com.abc.config.ApplicationConfig.getProperty(ApplicationConfig.kt:24)
	at com.abc.repository.util.DataSource.<init>(DataSource.kt:26)

**To Reproduce**
In order for me to reproduce this behavior I need:

1. Version of Cfg4k - com.jdiazcano.cfg4k:cfg4k-core:0.9.41
1. ConfigProvider - CachedConfigProvider
1. ConfigLoader - EnvironmentConfigLoader
1. ConfigSource - Environment Variables
1. Configuration files unless the source is a String  - Environment Variables
1. Any interfaces/dataclasses used for binding/getting - nope

As example, it is easy to get an easy prototype with all the 5 points in the list:
I have the following configs for a DB. 
```
        val url = Property("db.conn", "")
        val driverName = Property("db.driver.name", "org.postgresql.Driver")
        val userName = Property("db.username", "")
        val password = Property("db.password", "")
        val connectionTimeout = Property("db.conn.timeout.sec", TimeUnit.SECONDS.toMillis(30))
        val idleTimeout = Property("db.conn.idle.timeout.sec", TimeUnit.MINUTES.toMillis(10))
        val maxLifetime = Property("db.conn.max.lifetime.sec", TimeUnit.MINUTES.toMillis(30))
        val minimumIdle = Property("db.conn.minimum.idle", 4)
        val maximumPoolSize = Property("db.conn.maximum.pool.size", 32)
        val connectionTestQuery = Property("db.conn.test.query", "SELECT 1")


data class Property<T : Any>(
    val key: String,
    val default: T
)
I use cfg4k like the following:
 override fun <T : Any> getProperty(prop: Property<T>): T {

        return configProvider.get(prop.key, prop.default.javaClass, prop.default)
    }
```
It seems like when i am searching for 
val connectionTimeout = Property("db.conn.timeout.sec", TimeUnit.SECONDS.toMillis(30))
This value does not exist in my Environment Variables, and should return the default. 
it may be getting confused with 
val url = Property("db.conn", "")
Which does exist in the Environment Variables. 
Since it finds
ConfigObject(value=jdbc:postgresql://127.0.0.1:1234/abc) 
as root and then fails. 

This works on 0.9.3

Before the key in fun DefaultConfigLoader.get() was different
key = DB_CONN_TIMEOUT_SEC  - 0.9.3
key = DB.CONN.TIMEOUT.SEC  - 0.9.41
Before it wasnt split and now it is. 

**Expected behavior**
Since val connectionTimeout = Property("db.conn.timeout.sec", TimeUnit.SECONDS.toMillis(30))
does not exist it should return the default value. 

**Additional context**
Let me know if i am not using this Library correctly.

**Comment by jdiazcano** [comment]
If it worked in 0.9.3 then it seems definitely a bug which I'll take a look tomorrow.

But! I would say that it is a weird way of using the library, what would be the end result that you would like to get?

I would so something like:

```
interface Database {
    fun username(): String = ""
    fun password(): String = ""    
}

main() {
    val loader = ...
    val provider = ...
    val db = provider.bind<Database>("db")
    assert db.username() == "foo"
}
```

**Comment by jdiazcano** [comment]
Now that I take a second look:

```
        val url = Property("db.conn", "")
        val connectionTimeout = Property("db.conn.timeout.sec", TimeUnit.SECONDS.toMillis(30))
```

The bug is happening because you have "db.conn" and "db.conn.timeout.sec" and how it works is by splitting by dot and keep finding the child until it arrives to the latest one. BUT! here you have `db.conn` that has a value and children at the same time, something that isn't supported.

It might just work if you use the url as `db.conn.url`.

**Comment by credmond-git** [comment]
Thanks for looking into it. 
I have been treating the library as a key value store. I haven't been using the bind at all.
I have been exclusively using 
`configProvider.get(key,javaClass, default)`
I haven't had any major structure on my keys, they are more names, so they may violate some expectations the library has. 

I can change it to db.conn.url and i agree that it should fix the issue. But the behavior has changed since 0.9.3 (maybe it was a bug fix and maybe i am not using the library as you intend). It is your library and if this is the intended use, then i can close my bug. 

I will look into using the library properly :)

**Comment by jdiazcano** [comment]
Yeah, the library doesn't get along well with not having a proper structure. I'll look more into it anyways and I might even try to make it work somehow. For example cresting a brand new config loader that doesn't look by the dots and saves everything flattened. The problem with that would be when using it with a provider and binding, the rest should all work properly.

It is my library but it is open source, this means everyone has a voice! Don't close it yet as I would like to investigate a little bit more.

This changed in 0.9.4 where the environment config loader uses the same loading strategy as everything else so it works with binding properly.

**Comment by credmond-git** [comment]
Thanks I appreciate the effort and dedication that must be involved in writing and maintaining an open source library.
